### ISSUE TITLE
Need to fix release repository

### ISSUE THREAD

**Issue by romainvv** [Catch-up-TV-and-More/repository.catchuptvandmore#11]
Hello,

As you did in https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/issues/8 , you need to fix addons.xml for the release repo since kodi 20.0 is out. 
https://github.com/Catch-up-TV-and-More/repository.catchuptvandmore/blob/master/addons_xmls/release/addons.xml

Thanks :)

**Comment by An-Untitled-Developer** [comment]
yes

**Comment by joaopa00** [comment]
Devrait être résolu. Je ferme
