### ISSUE TITLE
Problème chaînes France tv

### ISSUE THREAD

**Issue by kdurand44** [Catch-up-TV-and-More/repository.catchuptvandmore#9]
Bonjour 
Je suis sur la dernière version beta 13 sur Kodi 19.4
Les chaînes de France Tv ne fonctionne plus. Ça me dit qu'il y a un problème de DRM et qu'il faut passer sur une version de kodi supérieure a la 18... Alors que je suis sur la 19...
Une idée svp ? :)
Merciii

**Comment by joaopa00** [comment]
Résolu dans la dernière béta.
